config/routes.rb
Rails.application.routes.draw do
	devise_scope :user do
    	root :to => "devise/sessions#new"
	end

	devise_for :admins, skip: :all
	devise_scope :admin do
		get '/admin_login' => 'devise/sessions#new', as: :new_admin_session
		post 'login' => 'devise/sessions#create', as: :admin_session
		delete 'logout' => 'devise/sessions#destroy', as: :destroy_admin_session
		# get 'signup' => 'devise_invitable/registrations#new', as: :new_admin_registration
		# post 'signup' => 'devise_invitable/registrations#create', as: :admin_registration
		# get 'signup/cancel' => 'devise_invitable/registrations#cancel', as: :cancel_admin_registration
		# get 'admin' => 'devise_invitable/registrations#edit', as: :edit_admin_registration
		# patch 'admin' => 'devise_invitable/registrations#update', as: nil
		# put 'admin' => 'devise_invitable/registrations#update', as: :update_admin_registration
		# delete 'admin' => 'devise_invitable/registrations#destroy', as: :destroy_admin_registration
		get 'password' => 'devise/passwords#new', as: :new_admin_password
		post 'password' => 'devise/passwords#create', as: :admin_password
		get 'password/edit' => 'devise/passwords#edit', as: :edit_admin_password
		patch 'password' => 'devise/passwords#update'
		put 'password' => 'devise/passwords#update', as: :update_admin_password
	end
	devise_for :users
	get 'users/:id/myteam' => 'users#myteam'
	get '/cancel' => 'users#cancel',as: :cancel
	put 'users/:id/is_deleted' => 'users#is_deleted'

	resources :teams do
		resources :team_members
		get 'people' => 'team_members#people', as: 'people'
        resources :tourings do
        	resources :touring_members
        end
    end
		# get 'teams/:team_id/team_members/:id/people' => 'team_members#people'
	# get 'teams/:team_id/team_members/:id/people' => 'team_members#people',as: ''

	resources :moto_infos
	resources :users
	resources :admins, :admin_users, :admin_teams, :abouts

	resources :rooms ,only:[:show]
	post "/room/create/:user_id" => "rooms#create" ,as:'room_create'
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/message.rb
class Message < ApplicationRecord
	after_create_commit { MessageBroadcastJob.perform_later self }
    belongs_to :user
    belongs_to :room
end

app/models/message_team.rb
class MessageTeam < ApplicationRecord
  after_create_commit { MessageTeamBroadcastJob.perform_later self }
  belongs_to :user
  belongs_to :team
end

app/models/message_touring.rb
class MessageTouring < ApplicationRecord
	after_create_commit { MessageTouringBroadcastJob.perform_later self }
	belongs_to :user
	belongs_to :touring
end

app/models/moto_info.rb
class MotoInfo < ApplicationRecord
	belongs_to :user
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord

	has_many :users
end

app/models/room.rb
class Room < ApplicationRecord
	has_many :messages
	has_many :entrys
end

app/models/team.rb
class Team < ApplicationRecord
	belongs_to :user
	attachment :team_image
	has_many :team_members, dependent: :destroy
	has_many :message_teams, dependent: :destroy
	has_many :tourings

	validates :team_name,    length: { minimum: 1 }
	validates :team_name,    length: { maximum: 20 }
	validates :team_introduction,    length: { maximum: 200 }
    validates :age_range,    length: { maximum: 20 }
end

app/models/team_member.rb
class TeamMember < ApplicationRecord

	enum is_team: { hold: 0, approval:1, bye:2}
	belongs_to :team
	belongs_to :user
	validates_uniqueness_of :user_id, scope: [:team_id]
	scope :approval, -> { where(is_team: :approval)}
end

app/models/touring.rb
class Touring < ApplicationRecord
	belongs_to :user
	belongs_to :team
	attachment :touring_image
	has_many :touring_members
	has_many :message_tourings
end

app/models/touring_member.rb
class TouringMember < ApplicationRecord
	belongs_to :user
	belongs_to :touring

	validates :user, uniqueness: { scope: :touring }

	def self.is_member?(touring, user)
		where(touring: touring, user: user ).any?
	end
end

app/models/user.rb
class User < ApplicationRecord

	belongs_to :prefecture, optional: true
	has_many :moto_infos
	attachment :profile_image
	has_many :messages
	has_many :entries
	has_many :teams
	has_many :team_members
	has_many :message_teams
	has_many :tourings
	has_many :touring_members
	has_many :message_tourings
	validates :prefecture_id, presence: true

    validates :nickname,    length: { minimum: 1 }
    validates :nickname,    length: { maximum: 16 }
    validates :user_name,    length: { minimum: 1 }
    validates :user_name,    length: { maximum: 16 }
    validates :user_introduction,    length: { maximum: 100 }



  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


          enum sex: { man: 1, woman: 2, other: 3}
end

app/controllers/team_members_controller.rb
class TeamMembersController < ApplicationController
  before_action :set_team_member, only: [:show, :edit, :update, :destroy]

  # GET /team_members
  # GET /team_members.json
  def index
    @team = Team.find(params[:team_id])
    @team_members = @team.team_members.approval
  end
  def show
  end

  def people
    @team = Team.find(params[:team_id])
    if @team.user == current_user
      @team_members = @team.team_members.hold
    else
      redirect_to teams_path
    end
  end
  # GET /team_members/new
  def new
    @user = User.find(current_user.id)
    @team = Team.find(params[:team_id])
    @team_member = TeamMember.new
  end

  # GET /team_members/1/edit
  def edit
  end
  # POST /team_members
  # POST /team_members.json
  def create
    @team = Team.find(params[:team_id])
    @team_member = TeamMember.new(team_member_params)
    @team_member.user_id = current_user.id
    if @team_member.save
        redirect_to team_path(@team), alert: "申請を送信しました！チームのページからリーダーのページに行き、メッセージを送ってみよう！"
    else
        redirect_to team_path(@team), alert: "すでに申請を送信しております。少々お待ちください。"
    end
  end

  # PATCH/PUT /team_members/1
  # PATCH/PUT /team_members/1.json
  def update
    @team_member.approval!
    redirect_to team_team_members_path(@team_member.team)

    # respond_to do |format|
    #   if @team_member.update(team_member_params)
    #     format.html { redirect_to @team_member, notice: 'Team member was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @team_member }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @team_member.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /team_members/1
  # DELETE /team_members/1.json
  def destroy
    @team_member.destroy
    redirect_to  team_team_members_path(@team_member.team)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team_member
      @team_member = TeamMember.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_member_params
      params.require(:team_member).permit(:user_id, :team_id, :request_comment, :is_team)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/moto_infos_helper.rb
module MotoInfosHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/team_members_helper.rb
module TeamMembersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tourings_helper.rb
module TouringsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/team_members/index.html.erb
<body class="team-page-back">

  <%= render 'users/header' %>
  <%= render 'users/footer' %>
  <div class="team_member-main">
      <h1>メンバー一覧</h1>

      <table class="myteam-th">
        <thead>
          <tr>
            <th>メンバー</th>
          </tr>

        </thead>

        <tbody>
          <% @team_members.each do |team_member| %>
            <tr>
              <td><%= link_to team_member.user.nickname , user_path(team_member.user.id),class: "member-link" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <%= link_to "戻る", team_path(@team.id), class: "back-link" %>
  </div>
</body>

app/views/team_members/new.html.erb
<body class="my-team-member-back">

  <%= render 'users/header' %>
  <%= render 'users/footer' %>
	<div class="team_member-main">
		<div>チームへ参加申請を送ろう!</div>


		<%= form_for([@team,@team_member]) do |f| %>

			<div>
				<%= f.hidden_field :team_id, :value => @team.id %>
			</div>

		    <div>
				<%= f.text_field :request_comment %>
			</div>
			<br><%= f.submit '申請を送る' %></br>

			<% end %>
	</div>
</body>

<%#= link_to 'Back', team_members_path %>

app/views/team_members/people.html.erb
<body class="team-page-back">

  <%= render 'users/header' %>
  <%= render 'users/footer' %>
  <div class="team_member-main">


    <h1>申請一覧</h1>

    <table class="myteam-th">
      <thead>
        <tr>
          <th>申請者</th>
          <th>申請コメント</th>
        </tr>

      </thead>

      <tbody>
        <% @team_members.each do |team_member| %>
          <tr>
            <td><%= link_to team_member.user.nickname , user_path(team_member.user.id),class: "member-link" %></td>
            <td><%= team_member.request_comment %></td>
            <td><%= link_to "承認", team_team_member_path(@team, team_member), method: :patch  %></td>
            <td><%= link_to "削除", team_team_member_path(@team, team_member), method: :delete %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to "戻る", team_path(@team.id), class: "back-link" %>
  </div>
</body>