config/routes.rb
Rails.application.routes.draw do
	devise_scope :user do
    	root :to => "devise/sessions#new"
	end

	devise_for :admins, skip: :all
	devise_scope :admin do
		get '/admin_login' => 'devise/sessions#new', as: :new_admin_session
		post 'login' => 'devise/sessions#create', as: :admin_session
		delete 'logout' => 'devise/sessions#destroy', as: :destroy_admin_session
		# get 'signup' => 'devise_invitable/registrations#new', as: :new_admin_registration
		# post 'signup' => 'devise_invitable/registrations#create', as: :admin_registration
		# get 'signup/cancel' => 'devise_invitable/registrations#cancel', as: :cancel_admin_registration
		# get 'admin' => 'devise_invitable/registrations#edit', as: :edit_admin_registration
		# patch 'admin' => 'devise_invitable/registrations#update', as: nil
		# put 'admin' => 'devise_invitable/registrations#update', as: :update_admin_registration
		# delete 'admin' => 'devise_invitable/registrations#destroy', as: :destroy_admin_registration
		get 'password' => 'devise/passwords#new', as: :new_admin_password
		post 'password' => 'devise/passwords#create', as: :admin_password
		get 'password/edit' => 'devise/passwords#edit', as: :edit_admin_password
		patch 'password' => 'devise/passwords#update'
		put 'password' => 'devise/passwords#update', as: :update_admin_password
	end
	devise_for :users
	get 'users/:id/myteam' => 'users#myteam'
	get '/cancel' => 'users#cancel',as: :cancel
	put 'users/:id/is_deleted' => 'users#is_deleted'

	resources :teams do
		resources :team_members
		get 'people' => 'team_members#people', as: 'people'
        resources :tourings do
        	resources :touring_members
        end
    end
		# get 'teams/:team_id/team_members/:id/people' => 'team_members#people'
	# get 'teams/:team_id/team_members/:id/people' => 'team_members#people',as: ''

	resources :moto_infos
	resources :users
	resources :admins, :admin_users, :admin_teams, :abouts

	resources :rooms ,only:[:show]
	post "/room/create/:user_id" => "rooms#create" ,as:'room_create'
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

	belongs_to :prefecture, optional: true
	has_many :moto_infos
	attachment :profile_image
	has_many :messages
	has_many :entries
	has_many :teams
	has_many :team_members
	has_many :message_teams
	has_many :tourings
	has_many :touring_members
	has_many :message_tourings
	validates :prefecture_id, presence: true

    validates :nickname,    length: { minimum: 1 }
    validates :nickname,    length: { maximum: 16 }
    validates :user_name,    length: { minimum: 1 }
    validates :user_name,    length: { maximum: 16 }
    validates :user_introduction,    length: { maximum: 100 }



  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


          enum sex: { man: 1, woman: 2, other: 3}
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


	def show
		@user = User.find(params[:id])
		@moto_infos = @user.moto_infos

		# @prefecture = Prefecture.find(params[:id])
		# @prefectures = @user.prefectures
	end
	def edit
	    @user = User.find(params[:id])
	  if @user.id != current_user.id
	     redirect_to user_path(current_user)
	 end
	end

	def update
	    @user = User.find(params[:id])
	    @user.update(user_params)
	    if admin_signed_in?
	    	redirect_to admins_path
	    else
	        redirect_to user_path(current_user)
	    end
		
	end
	def myteam
		@user = User.find(params[:id])
		@myteam = @user.team_members.approval
		@myteams = @user.team_members.hold

	end
	def cancel
		@user = current_user
	end


private 
 def user_params
     params.require(:user).permit(:nickname,:user_name,:sex,:prefecture_id,:user_introduction,:profile_image,:age,:email, :is_deleted )
 end

end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_footer.html.erb
  <footer>
    <div class= "footer">Copyright © Hello_Moto All Rights Reserved.</div>
  </footer>

app/views/users/_header.html.erb
<header>
  <div class="header-main none">
    <%= link_to "HELLO MOTO", user_path(current_user.id), class: "logo none" %>
    <%= link_to "新しいチームを見つけに行こう", teams_path, class: "header-link-japan none" %>
    <%= link_to "所属チーム一覧へ", "/users/#{current_user.id}/myteam",class: "header-link-japan-2 none" %>
    <%= link_to  "ログアウト", destroy_user_session_path, method: :delete, class: "header-link-japan-3 none" %>

  </div>
</header>


<div class="header none-big">
	<div class="header-main">
	<%= link_to "HELLO MOTO", user_path(current_user.id), class: "logo none-big" %>
	  <a class="nav-button" href="#">
	    <span></span>
	    <span></span>
	    <span></span>
	  </a>
	  <nav class="nav-wrap none-big">
	    <ul class="nav none-big">
	      <li><%= link_to "新しいチームを見つけに行こう", teams_path,  class: "nav-bar-head none-big" %></li>
	      <li><%= link_to "所属チーム一覧へ", "/users/#{current_user.id}/myteam", class: "nav-bar-head none-big" %></li></li>
	      <li><%= link_to  "ログアウト", destroy_user_session_path, method: :delete, class: "nav-bar-head none-big" %></li>
	    </ul>
	  </nav>
	</div>
</div>

app/views/users/_list.html.erb
  <footer>
    <div class= "footer">Copyright © Hello_Moto All Rights Reserved.</div>
  </footer>

app/views/users/cancel.html.erb
<body class="my-page-back">
    <%= render 'users/header' %>
    <div class="profile-main-cancel">
		<%= form_for(@user) do |f| %>
			<div class="container text-center quit">
				<h1>退会確認</h1>
				<label><%= f.radio_button :is_deleted, "false" %>退会しない</label>
				<label><%= f.radio_button :is_deleted, "true"  %>退会する</label>
				<%= f.submit '決定' %>
			</div>
		<% end %>
    </div>
    <%= render 'users/footer' %>
</div>

app/views/users/edit.html.erb
<body class="my-page-back">
  <%= render 'users/header' %>
    <div class="profile-main-edit">
	ユーザー編集


	<%= form_for(@user) do |f| %>
	    <div>
	        <%= f.attachment_field :profile_image %>
	    </div>

		<div>
			<h5>ユーザーID</h5>
			<%= f.text_field :user_name%>
		</div>

		<div>
			<h5>ニックネーム</h5>
			<%= f.text_field :nickname%>
		</div>

	    <div class="field">都道府県<br>
	        <%= f.collection_select :prefecture_id, Prefecture.all, :id, :name, include_blank: '選択して下さい' %>
	    </div>



		<div>
			<h5>自己紹介(40文字以内)</h5>
			<%= f.text_area :user_introduction %>
		</div>




		<%= f.submit '確定'%>
		<% end %>
		<%= link_to "マイページへ戻る", user_path(current_user), class: "back_to_mypage" %><br>
		<%= link_to "退会する", cancel_path, class: "back_to_mypage" %>

		
	</div>
<%= render 'users/footer' %>
</body>

app/views/users/myteam.html.erb
<div class="my-page-back">

  <%= render 'users/header' %>
  <%= render 'users/footer' %>
  <div class="motoinfo-main">

    <h4>所属チーム一覧</h4>
    <table class="myteam-th">
      <thead>
        <tr>
          <th>チーム名</th>
        </tr>

      </thead>

      <tbody>
        <% @myteam.each do |myteam| %>
          <tr>
            <td><%= link_to myteam.team.team_name, team_path(myteam.team), class: "moto-info-add"  %></td>
          </tr>
        <% end %>
      </tbody>
    </table>


    <h4>申請保留中</h4>
    <table class="myteam-th">
      <thead>
        <tr>
          <th>チーム名</th>
        </tr>

      </thead>

      <tbody>
        <% @myteams.each do |myteams| %>
          <tr>
            <td><%= link_to myteams.team.team_name, team_path(myteams.team), class: "moto-info-add"  %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to "戻る", :back, class: "moto-info-add"  %>
  </div>
</div>

app/views/users/show.html.erb
<body class="my-page-back">
  <%= render 'users/header' %>
  <%= render 'users/footer' %>


  <div class="profile-main">
      <%= attachment_image_tag @user, :profile_image, :fill, 200, 200,fallback: "no_image.jpg",size: '150x150',class: "top_image" %>
    <div class="my-page-name"><%= @user.nickname %> #<%= @user.user_name %></div>
    <div class="name-border"></div>
    <% if @user == current_user %>



      <%= link_to edit_user_path , class: "mypage-button" do %>
        <i class="fas fa-edit">編集</i>
      <% end %>

    <br>
    <div class="my-region">活動地域:<%= @user.prefecture.name %></div>
    <div class="my-introduction">
      <div class="intro-text">自己紹介</div>
      <br>
      <div class="intro-text-main"><%= @user.user_introduction %></div>
    </div>
    <div class="border-moto-info"></div>
    <div class="moto-info">
      <div class="moto-info-title">自分のバイク</div>
      <table class="moto-info-table">
        <thead>
          <tr>
            <th class="moto-info-th"></th>
            <th></th>
            <th></th>
            <th></th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @moto_infos.each do |moto_info| %>
            <tr  class="moto-info">
              <td class="moto-info-th"><%= moto_info.maker_name %></td>
              <td class="moto-info-th"><%= moto_info.moto_name %></td>
              <td class="moto-info-th"><%= moto_info.volume %>cc</td>
              <td class="moto-info-th">
                <div class="moto-info-delete-box">
                  <%= link_to  moto_info, method: :delete, data: { confirm: '削除しますか?' } , class: "moto-info-delete" do %>
                      <i class="far fa-trash-alt"></i>
                  <% end %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="moto-info-add-box">
          <%= link_to new_moto_info_path(current_user), class: "moto-info-add" do %>
            <i class="fas fa-plus-circle">車両を追加</i>
          <% end %>
      </div>
    </div>
    <div class="log-out-box">
      <%= link_to  destroy_user_session_path, method: :delete,class: "my_logout_btn" do %>
        <i class="fas fa-sign-out-alt">ログアウト</i>
      <% end %>
    </div>
  </div>
  <% else %>

  <%= link_to "メッセージ", room_create_path(@user.id), method:'POST',class: "message-btn" %>

  <div class="my-region">活動地域:<%= @user.prefecture.name %></div>
    <div class="my-introduction">
      <div class="intro-text">自己紹介</div>
      <br>
      <div class="intro-text-main"><%= @user.user_introduction %></div>
    </div>
  <div class="border-moto-info"></div>
  <table class="moto-info-table">
    <thead>
      <tr>
        <th class="moto-info-th"></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @moto_infos.each do |moto_info| %>
        <tr  class="moto-info">
          <td class="moto-info-th"><%= moto_info.maker_name %></td>
          <td class="moto-info-th"><%= moto_info.moto_name %></td>
          <td class="moto-info-th"><%= moto_info.volume %>cc</td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% end %>

</body>