config/routes.rb
Rails.application.routes.draw do
	devise_scope :user do
    	root :to => "devise/sessions#new"
	end

	devise_for :admins, skip: :all
	devise_scope :admin do
		get '/admin_login' => 'devise/sessions#new', as: :new_admin_session
		post 'login' => 'devise/sessions#create', as: :admin_session
		delete 'logout' => 'devise/sessions#destroy', as: :destroy_admin_session
		# get 'signup' => 'devise_invitable/registrations#new', as: :new_admin_registration
		# post 'signup' => 'devise_invitable/registrations#create', as: :admin_registration
		# get 'signup/cancel' => 'devise_invitable/registrations#cancel', as: :cancel_admin_registration
		# get 'admin' => 'devise_invitable/registrations#edit', as: :edit_admin_registration
		# patch 'admin' => 'devise_invitable/registrations#update', as: nil
		# put 'admin' => 'devise_invitable/registrations#update', as: :update_admin_registration
		# delete 'admin' => 'devise_invitable/registrations#destroy', as: :destroy_admin_registration
		get 'password' => 'devise/passwords#new', as: :new_admin_password
		post 'password' => 'devise/passwords#create', as: :admin_password
		get 'password/edit' => 'devise/passwords#edit', as: :edit_admin_password
		patch 'password' => 'devise/passwords#update'
		put 'password' => 'devise/passwords#update', as: :update_admin_password
	end
	devise_for :users
	get 'users/:id/myteam' => 'users#myteam'
	get '/cancel' => 'users#cancel',as: :cancel
	put 'users/:id/is_deleted' => 'users#is_deleted'

	resources :teams do
		resources :team_members
		get 'people' => 'team_members#people', as: 'people'
        resources :tourings do
        	resources :touring_members
        end
    end
		# get 'teams/:team_id/team_members/:id/people' => 'team_members#people'
	# get 'teams/:team_id/team_members/:id/people' => 'team_members#people',as: ''

	resources :moto_infos
	resources :users
	resources :admins, :admin_users, :admin_teams, :abouts

	resources :rooms ,only:[:show]
	post "/room/create/:user_id" => "rooms#create" ,as:'room_create'
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/message.rb
class Message < ApplicationRecord
	after_create_commit { MessageBroadcastJob.perform_later self }
    belongs_to :user
    belongs_to :room
end

app/models/message_team.rb
class MessageTeam < ApplicationRecord
  after_create_commit { MessageTeamBroadcastJob.perform_later self }
  belongs_to :user
  belongs_to :team
end

app/models/message_touring.rb
class MessageTouring < ApplicationRecord
	after_create_commit { MessageTouringBroadcastJob.perform_later self }
	belongs_to :user
	belongs_to :touring
end

app/models/moto_info.rb
class MotoInfo < ApplicationRecord
	belongs_to :user
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord

	has_many :users
end

app/models/room.rb
class Room < ApplicationRecord
	has_many :messages
	has_many :entrys
end

app/models/team.rb
class Team < ApplicationRecord
	belongs_to :user
	attachment :team_image
	has_many :team_members, dependent: :destroy
	has_many :message_teams, dependent: :destroy
	has_many :tourings

	validates :team_name,    length: { minimum: 1 }
	validates :team_name,    length: { maximum: 20 }
	validates :team_introduction,    length: { maximum: 200 }
    validates :age_range,    length: { maximum: 20 }
end

app/models/team_member.rb
class TeamMember < ApplicationRecord

	enum is_team: { hold: 0, approval:1, bye:2}
	belongs_to :team
	belongs_to :user
	validates_uniqueness_of :user_id, scope: [:team_id]
	scope :approval, -> { where(is_team: :approval)}
end

app/models/touring.rb
class Touring < ApplicationRecord
	belongs_to :user
	belongs_to :team
	attachment :touring_image
	has_many :touring_members
	has_many :message_tourings
end

app/models/touring_member.rb
class TouringMember < ApplicationRecord
	belongs_to :user
	belongs_to :touring

	validates :user, uniqueness: { scope: :touring }

	def self.is_member?(touring, user)
		where(touring: touring, user: user ).any?
	end
end

app/models/user.rb
class User < ApplicationRecord

	belongs_to :prefecture, optional: true
	has_many :moto_infos
	attachment :profile_image
	has_many :messages
	has_many :entries
	has_many :teams
	has_many :team_members
	has_many :message_teams
	has_many :tourings
	has_many :touring_members
	has_many :message_tourings
	validates :prefecture_id, presence: true

    validates :nickname,    length: { minimum: 1 }
    validates :nickname,    length: { maximum: 16 }
    validates :user_name,    length: { minimum: 1 }
    validates :user_name,    length: { maximum: 16 }
    validates :user_introduction,    length: { maximum: 100 }



  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


          enum sex: { man: 1, woman: 2, other: 3}
end

app/controllers/tourings_controller.rb
class TouringsController < ApplicationController

  # GET /tourings
  # GET /tourings.json
  def index
    @team = Team.find(params[:team_id])
    user_meta = @team.team_members.find_by(user: current_user.id)
    if user_meta.nil?
      redirect_to teams_path
      return
    end
    if user_meta.is_team == 1
       redirect_to teams_path
       return
    end
    @tourings = @team.tourings
  end

  # GET /tourings/1
  # GET /tourings/1.json
  def show
    @tourings = Touring.find(params[:id])
    @team = Team.find(params[:team_id])
    user_meta = @team.team_members.find_by(user: current_user.id)
    if user_meta.nil?
      redirect_to teams_path
      return
    end
    unless user_meta.is_team == 1
      @touring_member = TouringMember.find_by(user: current_user, touring: @tourings)
      @messages = @tourings.message_tourings.limit(20).order(created_at: :desc)
    else
      redirect_to teams_path
    end
  end

  # GET /tourings/new
  def new
    @user = current_user
    @team = Team.find(params[:team_id])
    user_meta = @team.team_members.find_by(user: current_user.id)
    if user_meta.nil?
      redirect_to teams_path
      return
    end
    unless user_meta.is_team == 1
      @touring = Touring.new
    else
      redirect_to teams_path
    end
  end

  # GET /tourings/1/edit
  def edit
    @tourings = Touring.find(params[:id])
  end

  # POST /tourings
  # POST /tourings.json
  def create
    @team = Team.find(params[:team_id])
    @touring = Touring.new(touring_params)
    @touring.user = current_user
    @touring.save
    redirect_to team_tourings_path(@team.id)
  end

  # PATCH/PUT /tourings/1
  # PATCH/PUT /tourings/1.json
  def update
    @team = Team.find(params[:team_id])
    @tourings = Touring.find(params[:id])
    @tourings.update(touring_params)
    redirect_to team_touring_path(team_id: @team.id, id: @tourings.id)


  end

  # DELETE /tourings/1
  # DELETE /tourings/1.json
  def destroy
    @touring.destroy
    respond_to do |format|
      format.html { redirect_to tourings_url, notice: 'Touring was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.


    # Never trust parameters from the scary internet, only allow the white list through.
    def touring_params
      params.require(:touring).permit(:touring_name, :user_id,:team_id,:touring_image,:destination,:touring_date,:touring_detail, :meet)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/moto_infos_helper.rb
module MotoInfosHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tourings_helper.rb
module TouringsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tourings/_form.html.erb
<%= form_with(model: touring, local: true) do |form| %>
  <% if touring.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(touring.errors.count, "error") %> prohibited this touring from being saved:</h2>

      <ul>
      <% touring.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tourings/edit.html.erb
<div class="touring-back">
    <%= render 'users/header' %>
    <%= render 'users/footer' %>
  <div class="team-main">
  	<div class="edit-text-touring">
		<h1>ツーリング情報</h1>
		<%= form_for(@tourings, url: "/teams/#{@tourings.team_id}/tourings/#{@tourings.id}", html: {method: 'PATCH'}) do |f| %>
		    <div>
		        <%= f.attachment_field :touring_image %>
		    </div>
		    <div>
		    	<h5>ツーリング名</h5>
		    	<%= f.text_area :touring_name %>
		    </div>
		    <div>
		    	<h5>待ち合わせ場所</h5>
		    	<%= f.text_field :meet %>
		    </div>

			<div>
				<h5>行き先</h5>
				<%= f.text_field :destination %>
			</div>
			<div>
				<h5>日付</h5>
				<%= f.text_field :touring_date %>
			</div>
		    <div>
				<h5>ツーリング内容</h5>
				<%= f.text_area :touring_detail %>
			</div>
			<%= f.submit %>


		<% end %>
		<%= link_to "戻る", team_touring_path(@tourings.team_id),class: "back-link" %>
	    </div>
	</div>
</div>

app/views/tourings/index.html.erb
<div class="touring-back-index">
  <%= render 'users/header' %>
  <%= render 'users/footer' %>
  <div class="touring-main">
    <div class="touring-index-box">
      <h1>ツーリング予定一覧</h1>
       <%= link_to "新しい予定を作成",new_team_touring_path(@team),class: "back-link"  %>

      <table class="myteam-th">
        <thead>
          <tr>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @tourings.each do |touring| %>
            <tr>
              <td><%= touring.touring_name  %></td>
              <td><%= touring.touring_date  %></td>
              <td><%= touring.destination  %></td>
              <td><%= link_to "詳細", team_touring_path(@team,touring.id),class: "back-link"  %></td>

            </tr>
          <% end %>
        </tbody>
      </table>

      <br>


      <%= link_to 'チームページに戻る', team_path(@team),class: "back-link"  %>
    </div>
  </div>
</div>

app/views/tourings/new.html.erb
<div class="touring-back">
    <%= render 'users/header' %>
    <%= render 'users/footer' %>
  <div class="touring-main">

		<h1>New Touring</h1>

		<%= form_for([@team,@touring]) do |f| %>
			<div>
				<%= f.hidden_field :team_id, :value => @team.id %>
			</div>
		    <div>
		    	<h5>ツーリング名</h5>
				<%= f.text_field :touring_name %>
			</div>
		    <div>
		    	<h5>待ち合わせ場所</h5>
		    	<%= f.text_field :meet %>
		    </div>

			<%= f.submit %>
		<% end %>
	</div>
</div>

app/views/tourings/show.html.erb
<div class="touring-back">
    <%= render 'users/header' %>
  <div class="team-main">
  <%= attachment_image_tag @tourings, :touring_image, :fill, 60,  60 ,fallback: "no_image.jpg",size: '150x150',class: "touring-top-image "  %><br>
  <p class="team-page-name"><%= @tourings.touring_name %></p><br>
  <div class="touring-box">
<!--     <p><%= @tourings.team.team_name %></p><br> -->
    <p>行き先:<%= @tourings.destination %></p><br>
    <p>日にち、待ち合わせ時間:<%= @tourings.touring_date %></p><br>
    <p>詳細:<br><%= @tourings.touring_detail %></p><br>
    <p>責任者:<%= @tourings.user.nickname %></p><br>
    <p>待ち合わせ場所<%= @tourings.meet %></p><br>
    <% unless TouringMember.is_member?(@tourings, current_user) %>
    	<%= link_to team_touring_touring_members_path(@tourings.team, @tourings), method: :POST,class: "back-link" do %>
        <i class="fas fa-user-plus">参加する</i>
    <% end %>
    	<% else  %>
    	<%= link_to team_touring_touring_member_path(@tourings.team, @tourings, @touring_member), method: :DELETE,class: "touring-des " do %>
        <i class="fas fa-user-minus">参加取り消し</i>
      <% end %>
    <% end %>
    <%= link_to edit_team_touring_path(@tourings.team_id),class: "back-link" do %>
       <i class="fas fa-edit">編集する</i>
    <% end %>
    <%= link_to team_touring_touring_members_path(@tourings.team, @tourings),class: "back-link" do %>
       <i class="fas fa-address-book">参加メンバー</i>
    <% end %>
    </div>
  <div class="map-touring">
    <h2>gmap</h2>


    <div id='map'>
    </div>

    <style>
    #map{
      height: 400px;
      width: 100%;
    }
    </style>

    <script>


    let map
    let geocoder

    function initMap(){
      geocoder = new google.maps.Geocoder()

      map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: -34.397, lng: 150.644},
      zoom: 15
      });

      codeAddress();
    }
    function codeAddress(){
      // 入力を取得
      let inputAddress = "<%= @tourings.meet %>"

      // geocodingしたあとmapを移動
      geocoder.geocode( { 'address': inputAddress}, function(results, status) {
        if (status == 'OK') {
    　　　　　　　　　　　　// map.setCenterで地図が移動
          map.setCenter(results[0].geometry.location);

    　　　　　　　　　　　　// google.maps.MarkerでGoogleMap上の指定位置にマーカが立つ
          var marker = new google.maps.Marker({
              map: map,
              position: results[0].geometry.location
          });
        } else {
          alert('Geocode was not successful for the following reason: ' + status);
        }
      });
    }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCLbShDmm__a_FMdqz1EXGpl8ZvKxMKMws&callback=initMap" async defer></script>
  </div>
  <div class="chat-touring">
  <h1>チャット</h1>

  <form>
    <label>何か話してみよう！</label><br>
    <input type="text" data-behavior="room_touring_speaker">
  </form>


  <div id='message_tourings' data-touring_id="<%= @tourings.id %>">
    <%= render @messages %>
  </div>
      <%= link_to "一覧へ戻る", team_tourings_path(@tourings.team_id),class: "back-link" %>
  </div>
</div>
    <%= render 'users/footer' %>
  </div>